name: Work

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: 
          - "3.12"

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Run tests
        run: pytest test_My_lib.py --html=report.html
      
      - uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: inf_laba3/report.html
      
      - uses: actions/upload-artifact@v4
        with:
          name: main-code
          path: inf_laba3/my_lib.py

      - uses: actions/upload-artifact@v4
        with:
          name: tests-code
          path: inf_laba3/test_My_lib.py